server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:4173,http://localhost:4174}
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Idempotency-Key
              - X-User-Id
              - X-Workspace-Id
              - X-Roles
              - X-Request-Id
              - X-Correlation-Id
            exposedHeaders:
              - X-Request-Id
              - X-Correlation-Id
              - X-Trace-Id
              - X-Processed-At
              - X-EventFlow-Db-Route
              - X-EventFlow-Replay-Lsn
              - X-EventFlow-Commit-Lsn
              - X-EventFlow-Entity-Version
              - X-EventFlow-Write-Pin-Until
            allowCredentials: false
            maxAge: 3600
      routes:
        - id: registration-service
          uri: ${REGISTRATION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/events/*/registrations/**,/api/v1/events/*/check-ins/**,/api/v1/events/*/attendance/**
        - id: event-service
          uri: ${EVENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/events/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8180/realms/eventflow}
          jwk-set-uri: ${OIDC_JWK_SET_URI:http://localhost:8180/realms/eventflow/protocol/openid-connect/certs}

eventflow:
  security:
    enabled: ${OIDC_ENABLED:false}
  public-weather:
    geolocation-url: ${PUBLIC_GEOLOCATION_URL:https://ipwho.is/}
    weather-url: ${PUBLIC_WEATHER_URL:https://api.open-meteo.com/v1/forecast}
    timeout: ${PUBLIC_WEATHER_TIMEOUT:5s}

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4173,http://localhost:4174}
        allowed-methods: GET,POST,PATCH,DELETE,OPTIONS
        allowed-headers: Authorization,Content-Type,Idempotency-Key,X-User-Id,X-Workspace-Id,X-Roles,X-Request-Id,X-Correlation-Id
        exposed-headers: X-Request-Id,X-Correlation-Id,X-Trace-Id,X-Processed-At,X-EventFlow-Db-Route,X-EventFlow-Replay-Lsn,X-EventFlow-Commit-Lsn,X-EventFlow-Entity-Version,X-EventFlow-Write-Pin-Until
        allow-credentials: false
        max-age: 3600
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
